CREATE TABLE inmobiliarias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    rfc VARCHAR(13),
    nombre_contacto VARCHAR(255),
    correo VARCHAR(255),
    telefono VARCHAR(50)
);
