CREATE TABLE propiedades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    direccion VARCHAR(255),
    observaciones TEXT,
    inmobiliaria_id BIGINT NOT NULL,
    CONSTRAINT fk_propiedad_inmobiliaria
        FOREIGN KEY (inmobiliaria_id)
        REFERENCES inmobiliarias (id)
);

CREATE INDEX idx_propiedades_inmobiliaria_id ON propiedades (inmobiliaria_id);
