CREATE TABLE personas (
    id_persona BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_persona VARCHAR(10) NOT NULL,
    nombre VARCHAR(150),
    apellidos VARCHAR(150),
    razon_social VARCHAR(200),
    rfc VARCHAR(13),
    curp VARCHAR(18),
    email VARCHAR(255),
    telefono VARCHAR(30),
    fecha_alta TIMESTAMP NOT NULL,
    activo BOOLEAN NOT NULL
);
